name: Daily USDA scrape

on:
  # manual Run‑workflow button
  workflow_dispatch:

  # run whenever anything is pushed to main
  push:
    branches:
      - main

  # run every day at 07:15 ET  (11:15 UTC)
  schedule:
    - cron: '15 11 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libraries
        run: pip install pandas requests

      - name: Run scraper
        run: python scraper.py
        env:
          USDA_API_KEY: ${{ secrets.USDA_API_KEY }}

      - name: Commit new CSVs
        run: |
          git config user.name "price-bot"
          git config user.email "bot@example.com"
          git add data || true
          git commit -m "Auto‑update $(date -u +'%F')" || echo "no changes"
          git push
